platform :ios, '6.0'

pod 'google-plus-ios-sdk'
pod 'AFNetworking', '~> 1.3.3'
pod 'SDWebImage'
pod 'Parse-iOS-SDK'
pod 'TestFlightSDK'
pod 'NSDate+TimeAgo'
pod 'FlurrySDK'
pod 'OHAttributedLabel'
pod 'Reachability', '~> 3.1.1'
pod 'Objective-C-HMTL-Parser', '~> 0.0.1'
pod 'WYPopoverController'
pod 'uidevice-extension'
pod 'YTVimeoExtractor'
pod 'MBProgressHUD'
pod 'BTBadgeView', '~> 1.2'
